version: '3.2'

networks:
  netsnear:
    driver: bridge
    ipam:
      driver: default
      config:
       - subnet: 10.172.31.0/24

services:
  app:
    hostname: appsneardev
    container_name: appsneardev
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: snearteam/appsneardev:v0.0.1
    depends_on:
     - db
     - cache
    restart: always
    volumes:
      - appsneardev_vol:/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: dev
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: pgsnearuser
      DB_PASSWORD: pgsnearpwd
      DB_NAME: dbsnear
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: snearredispassword
    links:
      - db
      - cache          
    networks:
      netsnear:

  db:
    hostname: dbsnear
    container_name: pgsneardb
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=pgsnearuser
      - POSTGRES_PASSWORD=pgsnearpwd
      - POSTGRES_DB=dbsnear
    ports:
      - '5432:5432'
    volumes: 
      - pgsnear_data:/var/lib/postgresql/data
    networks:
      netsnear:

  cache:
    image: redis:7.0-rc-alpine3.15
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning --requirepass snearredispassword
    volumes: 
      - redissnear_cache:/data
    networks:
      netsnear:
      
volumes:
  appsneardev_vol:
  pgsnear_data:
  redissnear_cache: